### ISSUE TITLE
PR count does not account all cases

### ISSUE THREAD

**Issue by jmMeessen** [jmMeessen/jenkins-hacktoberfest-stats#11]
As observed by  @lemeurherve, the current PR counter does not handle properly the case where any PR in repository with topic "hacktoberfest" should be counted. It is not necessary to tag all PRs with Hacktoberfest.

Note that dependabot/updatecli generated PR should be excluded from the count.

**Comment by lemeurherve** [comment]
> It is not necessary to tag all PRs with Hacktoberfest.

I would say that the tag should be applied only on PRs of repositories without "hacktoberfest" label. Doing more is unnecessary work and noise.

> Note that dependabot/updatecli generated PR should be excluded from the count.

To do so, exclude all PRs tagged with `dependencies`

**Comment by jmMeessen** [comment]
I stand corrected.

The rule states "YOUR PR/MRS MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR HAVE THE “HACKTOBERFEST-ACCEPTED” LABEL."

I have the impression that the rule evolved. Otherwise I don't understand how I missed that.

**Comment by jmMeessen** [comment]
The 7-day wait time (https://hacktoberfest.com/participation/) is also new since the site was published.

**Comment by lemeurherve** [comment]
> The rule states "YOUR PR/MRS MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR HAVE THE “HACKTOBERFEST-ACCEPTED” LABEL."

I'm saying the same:
- PRs in a repo tagged with "hackoberfest" are valid: in that (most common) case, only the repo need to be tagged, not the PRs.
- When the repo isn't tagged, the PRs must have an "hacktoberfest-accepted"

🙂

**Comment by jmMeessen** [comment]
closed with PR #13
